version: '3'

volumes:
  init-db:
  data-db:

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./data-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: mongo
    ports:
      - 27017:27017

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - mongo
    depends_on:
      - migration

  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/app
    links:
      - mongo
    depends_on:
      - make_migrations

  make_migrations:
    build: .
    command: python manage.py makemigrations
    volumes:
      - .:/app
    links:
      - mongo
    depends_on:
      - mongo
